### ISSUE TITLE
Forum de discussion

### ISSUE THREAD

**Issue by Raitoning** [Raitoning/ul-ppil#5]
Forum de discussion du projet. Venez poser vos questions ici, et mettre les notes de cours.

**Comment by Raitoning** [comment]
Commentaires du prof 12/04:
Remplacer "Cas d'utilisation" par "Liste des fonctionnalités" dans sommaire
Régler la numérotation dans le sommaire
Changer présentation du cahier des charges
Ajouter date, version, conditions et responsable du scénario
Créer un glossaire
Ajouter lettre groupe G
Déterminer fin des scénarios
Ajouter description des tâches
Tous les scénariospossibles
Nouvelles vues
Ajouter technologie utilisée
Ajouter GîtHub

**Comment by without2u** [comment]
[notes.txt](https://github.com/Raitoning/ul-ppil/files/1902336/notes.txt)

**Comment by Raitoning** [comment]
Demain RDV en 318 entre 9h et 10h ?

**Comment by without2u** [comment]
L’utilisateur s’identifie pour se connecter
Résumé : Un utilisateur possédant un compte peut s’identifier sur la page de connexion afin d’avoir accès
 à son espace personnel et naviguer sur le site, en cas de perte de mot de passe une page lui permet de 
recevoir ce dernier par email. (voir Vue)
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur non connecté.
Responsables : Groupe G 
Préconditions : L'utilisateur n'est pas connecté.  
Post conditions :  L’utilisateur est connecté.


L’utilisateur s’inscrit à la plateforme
Résumé : Un utilisateur pas encore inscrit peut-être rediriger depuis la page de connexion sur la page
 d’inscription en cliquant sur le lien approprié, ainsi il devra remplir les éléments présentés afin de
 s’enregistrer (une confirmation sera envoyée par email), les informations nécessaires sont (voir Vue) :
— Nom
— Email
— Mot de passe
— Confirmation mot de passe
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur non connecté.
Responsables : Groupe G 
Préconditions : L'utilisateur n'est pas connecté.  
Post conditions :  Le mail de validation a été envoyé.



L’utilisateur consulte sa liste personnelle
Résumé : Un utilisateur venant de se connecter est redirigé vers la page d’accueil cette dernière contient plusieurs
liens vers le reste du site : événement, gestion de compte et liste des utilisateurs mais également une liste trier
par date décroissantes des taches affecté a l’utilisateurs dans l’ensemble des événements auquel il participe. (Voir Vue)
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur connecté.
Responsables : Groupe G 
Préconditions : L'utilisateur est connecté sur sa page d'accueil.  
Post conditions :  L'utilisateur est sur sa la page de sa liste personnelle.



L’utilisateur consulte la liste d’utilisateurs et gère ses favoris
Résumé : Un utilisateur déjà connecté peut depuis la page d’accueil avoir accès à la liste de ses favoris et la liste des autres
 utilisateurs du site, (divers tris sont à disposition pour faciliter la recherche). Il peut également ajouter un 
utilisateur dans ses favoris en cliquant sur l’étoile à côté de son nom, à l’inverse on peut supprimer un favoris de 
la même manière.
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur connecté.
Responsables : Groupe G 
Préconditions : L'utilisateur est la page de liste des utilisateurs.  
Post conditions : la liste des favoris est à jour. 



L’utilisateur gère son compte
Une fois un utilisateur identifié, il peut gérer son comtpe, en changeant de :
— mot de passe
— email
— nom
Ou en supprimant le compte
Il a acces a cette focntionnalité de puis le menu d’accueil en clioquant sur l’icone "compte".(voir Vue)
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur connecté.
Responsables : Groupe G 
Préconditions : L'utilisateur est sur sa page de profil.  
Post conditions : Le profil de l’utilisateur est à jour. 




L’utilisateur consulte les évènements publics
Résumé : Un utilisateur non connecté peux tout de même avoir accès a la liste des événements publics depuis la page 
de connexion et les consulter.
Pour un utilisateur connecté, il peux cliquer sur le lien "événement" puis sur "événement publics" pour avoir 
accès également a cette liste.
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur non connecté ,utilisateur connecté.
Responsables : Groupe G 
Préconditions : L'utilisateur est sur la page de connexion.  
Post conditions : l'utilisateur est sur la page de la liste des événements pulics



L’utilisateur s’inscrit à un évènement public
Résumé : Un utilisateur (connecté ou non) peux cliquer sur un évènement de la liste pour avoir accès à sa description complète,
il pourras s’y inscrire (mais uniquement s’il est déjà connecté).(voir Vue)
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur connecté.
Responsables : Groupe G 
Préconditions : l'utilisateur est sur la page de la liste des événements pulics.  
Post conditions : le systeme previent le propriétaire.


L’utilisateur accepte une invitaion
Résumé : Un utilisateur reçois un email contenant un lien de validation lorsqu’on l’invite ce dernier a un événement, 
le lien le redirige vers une page ou il auras les description de l’invitation et pourra l’accepter ou la refuser,
en cas d’acceptation il pourra avoir par la suite accès a la page de l’événement depuis son compte.(voir Vue)
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur connecté.
Responsables : Groupe G 
Préconditions : l'utilisateur est connecté sur la page de description d'invitations.  
Post conditions : le systeme previent le propriétaire .


L’utilisateur consulte sa liste d’évènements
Un utilisateur peux consulter la liste des événements auquel il participe en allant sur la page "événement" depuis son
accueil; a droite de l’écran, la liste de tout ses événements en cour (public et privé) sera affiché, il aura juste a 
cliquer sur celui qui l’intéresse afin d’avoir accès a la page de description de l’événement (page identique dans le cas
d’un événement public ou privé).(voir Vue)
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur connecté,utilisateur non connecté.
Responsables : Groupe G 
Préconditions : l'utilisateur est connecté sur la page d'accueil.  
Post conditions : l'utilisateur est sur sa page des événements.


L’utilisateur se désinscrit d’un évènement
Résumé : Un utilisateur inscrit a un événement peux se désinscrire en cliquant sur le bouton "désinscription", 
celà aura pour effet de supprimer l’événement de ça liste d’événement ainsi que les taches de ça liste de taches
personnalisée. (voir Vue)
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur connecté.
Responsables : Groupe G 
Préconditions : l'utilisateur est connecté sur la page de sa liste des événements.  
Post conditions : le systéme previent le propriétaire.


L’utilisateur crée un évènement
Résumé : Un utilisateurs peux créer un événement en cliquant sur le liens "création d’événement" de la page gestion d’événement,
il devra donc remplir le nom et la date de debut. De manière facultative il pourra également indiqué une date de fin, 
une liste d’invités et une liste de tâches à faire.
De base le type d’événement est privé, mais il peut le passer en public en cochant la case correspondante.
Et peux empêcher la suppression de l’événement après ça date de fin (si il y en a une renseignée) .(voir Vue)
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : propriétaire.
Responsables : Groupe G 
Préconditions : l'utilisateur est connecté sur la page de gestion d'événements.  
Post conditions : le systéme valide la creation de l'événement.


L’utilisateur gère un évènement
Résumé : Si l’utilisateur va sur la page d’un événement où il est propriétaire ou à les droit de gestion, il pourra cliquer sur un petit engrenage afin d’avoir accès a la page de modification de cet événement, la il pourra :
— ajouter des utilisateur
— ajouter des tache
— supprimer des tache
— modifier des tache
— retirer un utilisateur de l’événement
Plus particulièrement pour le propriétaire il pourra en plus :
— modifier la date de début
— modifier la date de fin
— modifier le nom de l’événement
— modifier le type de l’événement (privé ou public)
— supprimer l’événement
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : éditeur, propriétaire.
Responsables : Groupe G 
Préconditions : l'utilisateur est connecté sur la page de gestion d'événements.  
Post conditions : l'événement est à jour ,et le systéme valide les changements.


Un utilisateur connecté souhaite se déconnecter
Résumé :L’utilisateur peut se déconnecter du site.(voir Vue) 
Date de création : 9/04/18 
Date de mise à jour : 12/04/18  
Version : 1.0  
Acteurs : utilisateur connecté.
Responsables : Groupe G 
Préconditions : l'utilisateur est connecté .  
Post conditions : l'utilisateur est déconnecté , sur la page d'accueil du site.

**Comment by Raitoning** [comment]
Rendu et présentation du cahier des charges                                           
par Mathieu Constant, jeudi 12 avril 2018, 11:50

Bonjour à tous, Dans l'optique de la présentation de vos cahiers des charges à l'oral mardi 17 avril 2018 à 9h, nous vous remercions de déposer sur Arche les documents suivants: 

- votre cahier des charges au format pdf, avant le lundi 16 avril 2018, 18h 
- les supports de votre présentation orale au format pdf, avant mardi 17 avril 2018 9h. Un dépôt unique par groupe est obligatoire.  

 Lors de la présentation orale, chaque groupe disposera de 10  min pour présenter son cahier des charges (lister les fonctionnalités,  détailler au moins 4 fonctionnalités importantes an utilisant les vues  appropriées). Chaque présentation sera suivie de 5 min de  questions/commentaires. Pour rappel, le cahier des charges déposé et la  présentation donneront lieu à une première évaluation. 

Bien cordialement, Mathieu Constant et Phuc Ngo

**Comment by formotiis** [comment]
[PPIL_cahier (1).pdf](https://github.com/Raitoning/ul-ppil/files/1914896/PPIL_cahier.1.pdf)
Temporary version

**Comment by harryless17** [comment]
Scenario : Accepter une invitation
Scenario normal :
-Apres réception du mail, l’utilisateur choisit de cliquer sur le lien 
-L’utilisateur est renvoyé vers la page de validation d’invitation 
-L’utilisateur décide d’accepter ou non l’invitation
Scenario Exceptionnel :
L’évènement à été supprimé avant que l’utilisateur n'accepte l’invitation  


Résumé de la suppression d’un évènement par un utilisateur connecté :
L’utilisateur connecté propriétaire d’un évènement peut décider de supprimer un évènement
Date de création : 9/04/18 
Date de mise à jour : 16 avril 2018
 Version : 1.0 
Acteurs : utilisateur connecté propriétaire .
 Responsables : Groupe G 
Préconditions : l’évènement existe 
Post conditions : l’évènement est supprimé. 


Résumé du partage d’un évènement 
L’utilisateur connecté propriétaire ou ayant droit d’Edition peut partager un évènement avec un autre utilisateur 
Date de création : 9/04/18 
Date de mise à jour : 16 avril 2018
 Version : 1.0 
Acteurs : utilisateur connecté propriétaire ou éditeur .
Responsables : Groupe G 
Préconditions : l’évènement existe 
Post conditions : l’évènement est partagé.

**Comment by without2u** [comment]
travail a faire :

- ajout des maquettes pour les scenarios alternative et exceptionnel
- correction de certin scenario et fonctionnalité 
- ajout des fonctionalités :creation et gestion des taches
